In [1]:
#crosstab is a type of table in a matrix format that displays the frequency distribution of the variable
import pandas as pd
df=pd.read_excel("survey.xlsx")
df

                   name    state  age sex handedness
0               rajasri       AP   22   F          R
1             rakshitha       AP   22   F          R
2               suvarna       AP   22   F          R
3                  neha       AP   22   F          R
4                nithya       AP   22   F          R
5               shabnam       AP   22   F          R
6               neeraja       AP   21   F          R
7                    ss       MH   22   M          R
8   shantanu maheshwari       WB   34   M          R
9         shruti sinha     Delhi   27   F          R
10       parth samthan        MH   34   M          L
11                  srk    Delhi   59   M          L
12          mohit raina  Kashmir   44   M          L
13     saurabh raj jain       MH   38   M          L
14     aditi dev sharma   Punjab   44   F          L

In [6]:
#.crosstab(df.columnname to be on xaxis,df.columnname to be on yaxis)
pd.crosstab(df.state,df.handedness)
pd.crosstab(df.state,df.handedness,margins=True)
#now in both x , y axis we have only 1 , but what if we want to see 2(attributes in row or column then )
pd.crosstab([df.state,df.sex],[df.handedness,df.age],margins=True)
#if u wanna know the parameters need to be passed into a method then , place ur cursor in between the method name and click shift+tab then u will get the description of the method u require 
pd.crosstab(df.state,df.handedness,normalize='index')

handedness         L         R
state
AP          0.000000  1.000000
Delhi       0.500000  0.500000
Kashmir     1.000000  0.000000
MH          0.666667  0.333333
Punjab      1.000000  0.000000
WB          0.000000  1.000000

In [7]:
import numpy as np
#to find the avg age of female and male handedes
pd.crosstab(df.sex,df.handedness,values=df.age,aggfunc=np.average)

handedness      L     R
sex
F           44.00  22.5
M           43.75  28.0