In [4]:
import pandas as pd
#we have .read_csv() method this will convert .csv file into dataframe , the inputs for this method will be file name if it is present in same folder , else provide the path of the .csv file
df=pd.read_csv("name.csv")
df
#import os 
#os.getcwd()#
#Feature	CSV	Excel
#File Extension	.csv	.xls / .xlsx
#Type	Plain text	Binary / XML
#Multiple Sheets	❌	✅
#Formatting & Formulas	❌	✅
#File Size	Small	Larger
#Compatibility	Universal	Mainly Microsoft Excel
#Best For	Data storage, data transfer	Data analysis, visualization

#Excellent question — and yes, you can create both .csv and .xlsx files using Excel itself, but there are also other ways to create them (like using programming languages or online tools).

   SNO       Name  Birthdate
0    1    Rajasri  05-08-2003
1    2  Rakshitha   29.9.2003
2    3     Vasavi  17.11.2005
3    4    Suvarna  19.12.2003
4    5       Neha    3.9.2003
5    6     Nithya  23.10.2003
6    7    Shabnam   22.8.2003
7    8     Tharak   11.6.2014
8    9     Vikram   13.3.2019
9   10         SS    4.6.2003

In [ ]:
#this is the way to create .csv file and excel file through the data
data = {'Name': ['Ravi', 'Priya'], 'Age': [22, 24]}
# Create a CSV file
df = pd.DataFrame(data)
df.to_csv('data.csv', index=False)
# Create an Excel file
df.to_excel('data.xlsx', index=False)

# Reading a CSV file
df_csv = pd.read_csv("data.csv")
# Reading an Excel file
df_excel = pd.read_excel("data.xlsx")

In [3]:
#3rd way to create a dataframe is by using dictionary
rs={'name':["rajasri","jaihanuman"],'type':['humanbeing','god']}
df=pd.DataFrame(rs)
df

         name        type
0     rajasri  humanbeing
1  jaihanuman         god

In [7]:
#4th way to create a data frame is to create from list of tuple and here we need to give column name also 
wd=[(1,'rs',5),(2,'rk',29)]
df=pd.DataFrame(wd,columns=["SNO",'NAME_SHORTCUTS','BD'])
df

   SNO NAME_SHORTCUTS  BD
0    1             rs   5
1    2             rk  29

In [8]:
#5th way to create data frame is to create form dictionary 
wd=[{'sno':1,'ns':'rs','bd':5},{'sno':2,'ns':'rk','bd':29}]
df=pd.DataFrame(wd)
df

   sno  ns  bd
0    1  rs   5
1    2  rk  29